# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# NOTE: Run only for Mango without uwsm
# exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

exec-once = uwsm-app -- qs -c noctalia-shell

exec-once = uwsm-app -- wl-paste --type text --watch cliphist store
exec-once = uwsm-app -- wl-paste --type image --watch cliphist store
exec-once = uwsm-app -- fcitx5 -d

exec-once = uwsm-app -- bash -c 'until systemctl is-active --quiet --user arrpc.service; do sleep 1; done && sleep 7 && flatpak run dev.vencord.Vesktop'
exec-once = uwsm-app -- gio launch ~/.local/share/applications/com.google.Chrome.flextop.chrome-hnpfjngllnobngcgfapefoaidbinmjnm-Default.desktop
