# More option see https://github.com/DreamMaoMao/mango/wiki/

source = ~/.config/mango/input.conf

source = ~/.config/mango/env.conf

source = ~/.config/mango/monitors.conf

source = ~/.config/mango/style.conf

source = ~/.config/mango/autostart.conf

source = ~/.config/mango/workspaces.conf

source = ~/.config/mango/windows.conf

source = ~/.config/mango/keybinds.conf
